Relax the criteria for short-circuit
w3c/process pull request #885
Opened 2024-06-18 05:54 UTC by frivoal

A high bar for support remains needed, and any dissent remains sufficient to defeat the short-circuit proposal, but unanimity is no longer required.

See https://github.com/w3c/process/issues/852

***
<a href="https://pr-preview.s3.amazonaws.com/frivoal/w3process/pull/885.html" title="Last updated on Jul 10, 2024, 3:31 PM UTC (4bd549e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/process/885/50ce7b7...frivoal:4bd549e.html" title="Last updated on Jul 10, 2024, 3:31 PM UTC (4bd549e)">Diff</a>

2024-06-18 22:00 UTC, TallTed requested changes
hopefully clarifying language tweak

2024-06-18 22:00 UTC, TallTed commented on index.bs
> +	* none of them vote against adopting the resolution
```suggestion
	confirm it by a vote which results in both of the following:
	* at least 80% of them vote affirmatively to adopt this resolution
	* none of them vote against adopting the resolution
```

2024-06-18 22:00 UTC, TallTed commented on index.bs
> +	which ever is shortest.
```suggestion
	whichever is shortest.
```

2024-06-25 23:57 UTC, fantasai requested changes
The intention was to reduce the threshold to allow people to be absent (e.g. on vacation or whatever), not to introduce the option of abstaining, so I think we shouldn't say that it's possible.

2024-06-26 00:02 UTC, fantasai commented on index.bs
> +	has responded (including explicit votes to abstain),
```suggestion
	has voted,
```

2024-07-10 15:31 UTC, frivoal commented on index.bs
> +	The request for confirmation <em class=rfc2119>must</em> be open for two weeks,
```suggestion
	The request for confirmation <em class=rfc2119>must</em> be open for a period of at least two weeks,
```

2024-07-10 15:33 UTC, merged

2024-07-16 21:52 UTC, tantek reviewed
LGTM